# Generated by Django 4.1 on 2022-09-11 10:49

import ads.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_location_lat_alter_location_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="def_cat",
                max_length=10,
                validators=[django.core.validators.MinValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                null=True, validators=[ads.validators.check_birth_date]
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[ads.validators.check_email_address],
            ),
        ),
    ]
